# GENERATED FILE. DO NOT EDIT.

###
### Begin CMakeLibraryFunctions.cmake
###

# Set the flags necessary to reach the given C/C++ compiler level
function (cdepRequireMinimumCxxCompilerStandard target level)
    target_compile_options(${target} PRIVATE $<$<COMPILE_LANGUAGE:CXX>:-std=c++${level}>)
endfunction()

###
### End CMakeLibraryFunctions.cmake
###

###
### Add dependency for CDep module: com.github.jomof:freetype:2.6.2-rev14
###
if(FREETYPE_CDEP_COORDINATE)
  message(FATAL_ERROR "CDep module '${FREETYPE_CDEP_COORDINATE}' was already defined")
endif(FREETYPE_CDEP_COORDINATE)
set(FREETYPE_CDEP_COORDINATE "com.github.jomof:freetype:2.6.2-rev14")
set(FREETYPE_ROOT "/Users/gauravk/.cdep/exploded/com.github.jomof/freetype/2.6.2-rev14/headers.zip/include")
function(add_cdep_freetype_dependency target)
  # Choose between Android NDK Toolchain and CMake Android Toolchain
  set(cdep_supports_compiler_features TRUE)
  if(NOT CMAKE_SYSTEM_VERSION EQUAL 1)
    set(cdep_determined_android_runtime ${CMAKE_ANDROID_STL_TYPE})
    set(cdep_determined_android_abi ${CMAKE_ANDROID_ARCH_ABI})
    set(cdep_determined_android_platform_level ${CMAKE_SYSTEM_VERSION})
  else()
    set(cdep_determined_android_runtime ${ANDROID_STL})
    set(cdep_determined_android_abi ${ANDROID_ABI})
    set(cdep_determined_android_platform_level ${ANDROID_PLATFORM_LEVEL})
    set(cdep_supports_compiler_features FALSE)
  endif()

  set(cdep_exploded_root "/Users/gauravk/.cdep/exploded")
  set(coordinate_group_id "com.github.jomof")
  set(coordinate_artifact_id "freetype")
  set(coordinate_version "2.6.2-rev14")
  set(exploded_archive_tail "${coordinate_group_id}/${coordinate_artifact_id}/${coordinate_version}")
  set(exploded_archive_folder "${cdep_exploded_root}/${exploded_archive_tail}")

  execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/headers.zip 303229 6f8159c419ba9600827697c90a59de68b563adf0cb9fef5435a499328f14e9d8)
  target_include_directories(${target} PUBLIC "${exploded_archive_folder}/headers.zip/include")

  if(CMAKE_SYSTEM_NAME STREQUAL "Android")
    if(cdep_determined_android_runtime STREQUAL "c++_shared")
      if(cdep_determined_android_platform_level GREATER 20)
        if(cdep_determined_android_abi STREQUAL "armeabi")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-cxx-platform-21-armeabi.zip 369033 1d20827c589d35b8aac7445e9c35c32479591a4802d8050a0b578f8eeb432908)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-cxx-platform-21-armeabi.zip/lib/armeabi/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "armeabi-v7a")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-cxx-platform-21-armeabi-v7a.zip 335629 2b0f9a17b3793efb4fd9174f55852d7b8b6e594afedc0bb479071c137afc8f84)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-cxx-platform-21-armeabi-v7a.zip/lib/armeabi-v7a/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "arm64-v8a")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-cxx-platform-21-arm64-v8a.zip 374701 a0672b0ce2ce2a932ffe7998c6203ebfecd804cd378cb9e5c83f00a93b0dbe82)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-cxx-platform-21-arm64-v8a.zip/lib/arm64-v8a/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "x86")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-cxx-platform-21-x86.zip 378894 6db4af622adcd938cf39eb5c95523c8e6b984d09271f40add478bcdee5e4562a)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-cxx-platform-21-x86.zip/lib/x86/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "x86_64")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-cxx-platform-21-x86_64.zip 395132 e4a6c218dc85904f11ff599f5eefcaabdc89d11e5c6f589c4d41a7000fd42b60)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-cxx-platform-21-x86_64.zip/lib/x86_64/libfreetype.a")
        else()
          message(FATAL_ERROR "Android ABI ${cdep_determined_android_abi} is not supported by com.github.jomof:freetype:2.6.2-rev14 for platform ${cdep_determined_android_platform_level}. Supported: armeabi armeabi-v7a arm64-v8a x86 x86_64  CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
        endif()
      elseif(cdep_determined_android_platform_level GREATER 11)
        if(cdep_determined_android_abi STREQUAL "armeabi")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-cxx-platform-12-armeabi.zip 369025 2588edf3e855fc89e858a40b0c9a8b7e5f4778681bf55d727c209b3d610a2d37)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-cxx-platform-12-armeabi.zip/lib/armeabi/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "armeabi-v7a")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-cxx-platform-12-armeabi-v7a.zip 335630 a0c776b84f32640c49f4a064a98df8b30f1c5c7e979f672ff56f103f730b1821)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-cxx-platform-12-armeabi-v7a.zip/lib/armeabi-v7a/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "x86")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-cxx-platform-12-x86.zip 378892 2601b9f9d2f738a3880d1bb7e5d2e3debc8d41f61c04d12e27dfe9705c231d14)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-cxx-platform-12-x86.zip/lib/x86/libfreetype.a")
        else()
          message(FATAL_ERROR "Android ABI ${cdep_determined_android_abi} is not supported by com.github.jomof:freetype:2.6.2-rev14 for platform ${cdep_determined_android_platform_level}. Supported: armeabi armeabi-v7a x86  CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
        endif()
      else()
        message(FATAL_ERROR "Android API level ${cdep_determined_android_platform_level} is not supported by com.github.jomof:freetype:2.6.2-rev14 CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
      endif()
    elseif(cdep_determined_android_runtime STREQUAL "c++_static")
      if(cdep_determined_android_platform_level GREATER 20)
        if(cdep_determined_android_abi STREQUAL "armeabi")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-cxx-platform-21-armeabi.zip 369033 1d20827c589d35b8aac7445e9c35c32479591a4802d8050a0b578f8eeb432908)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-cxx-platform-21-armeabi.zip/lib/armeabi/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "armeabi-v7a")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-cxx-platform-21-armeabi-v7a.zip 335629 2b0f9a17b3793efb4fd9174f55852d7b8b6e594afedc0bb479071c137afc8f84)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-cxx-platform-21-armeabi-v7a.zip/lib/armeabi-v7a/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "arm64-v8a")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-cxx-platform-21-arm64-v8a.zip 374701 a0672b0ce2ce2a932ffe7998c6203ebfecd804cd378cb9e5c83f00a93b0dbe82)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-cxx-platform-21-arm64-v8a.zip/lib/arm64-v8a/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "x86")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-cxx-platform-21-x86.zip 378894 6db4af622adcd938cf39eb5c95523c8e6b984d09271f40add478bcdee5e4562a)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-cxx-platform-21-x86.zip/lib/x86/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "x86_64")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-cxx-platform-21-x86_64.zip 395132 e4a6c218dc85904f11ff599f5eefcaabdc89d11e5c6f589c4d41a7000fd42b60)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-cxx-platform-21-x86_64.zip/lib/x86_64/libfreetype.a")
        else()
          message(FATAL_ERROR "Android ABI ${cdep_determined_android_abi} is not supported by com.github.jomof:freetype:2.6.2-rev14 for platform ${cdep_determined_android_platform_level}. Supported: armeabi armeabi-v7a arm64-v8a x86 x86_64  CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
        endif()
      elseif(cdep_determined_android_platform_level GREATER 11)
        if(cdep_determined_android_abi STREQUAL "armeabi")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-cxx-platform-12-armeabi.zip 369025 2588edf3e855fc89e858a40b0c9a8b7e5f4778681bf55d727c209b3d610a2d37)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-cxx-platform-12-armeabi.zip/lib/armeabi/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "armeabi-v7a")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-cxx-platform-12-armeabi-v7a.zip 335630 a0c776b84f32640c49f4a064a98df8b30f1c5c7e979f672ff56f103f730b1821)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-cxx-platform-12-armeabi-v7a.zip/lib/armeabi-v7a/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "x86")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-cxx-platform-12-x86.zip 378892 2601b9f9d2f738a3880d1bb7e5d2e3debc8d41f61c04d12e27dfe9705c231d14)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-cxx-platform-12-x86.zip/lib/x86/libfreetype.a")
        else()
          message(FATAL_ERROR "Android ABI ${cdep_determined_android_abi} is not supported by com.github.jomof:freetype:2.6.2-rev14 for platform ${cdep_determined_android_platform_level}. Supported: armeabi armeabi-v7a x86  CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
        endif()
      else()
        message(FATAL_ERROR "Android API level ${cdep_determined_android_platform_level} is not supported by com.github.jomof:freetype:2.6.2-rev14 CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
      endif()
    elseif(cdep_determined_android_runtime STREQUAL "gnustl_shared")
      if(cdep_determined_android_platform_level GREATER 20)
        if(cdep_determined_android_abi STREQUAL "armeabi")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-gnustl-platform-21-armeabi.zip 369041 bdb5e3e80b85b24fb635bc214c319ee71043c22ef1943f157353b512e069e4f7)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-gnustl-platform-21-armeabi.zip/lib/armeabi/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "armeabi-v7a")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-gnustl-platform-21-armeabi-v7a.zip 335622 98674f947353852ae5440491a8f73f33ccc480a7aea4f20b6e0a82b71f300417)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-gnustl-platform-21-armeabi-v7a.zip/lib/armeabi-v7a/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "arm64-v8a")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-gnustl-platform-21-arm64-v8a.zip 374694 8971488ad8f9af7ba1a51fd060fe8e167fe706fa7676c6f0c13a407f775b6ea0)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-gnustl-platform-21-arm64-v8a.zip/lib/arm64-v8a/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "x86")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-gnustl-platform-21-x86.zip 378894 4293869f6aaec95f1428af3c5add6d6982be7cd4fcadac2aff1b718c659d4687)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-gnustl-platform-21-x86.zip/lib/x86/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "x86_64")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-gnustl-platform-21-x86_64.zip 395151 608dfb496a36aa2ebdd10c0175617e4ec41deedade88eafe4340c64455b9bb5b)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-gnustl-platform-21-x86_64.zip/lib/x86_64/libfreetype.a")
        else()
          message(FATAL_ERROR "Android ABI ${cdep_determined_android_abi} is not supported by com.github.jomof:freetype:2.6.2-rev14 for platform ${cdep_determined_android_platform_level}. Supported: armeabi armeabi-v7a arm64-v8a x86 x86_64  CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
        endif()
      elseif(cdep_determined_android_platform_level GREATER 11)
        if(cdep_determined_android_abi STREQUAL "armeabi")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-gnustl-platform-12-armeabi.zip 369035 3e09bf646af1a7614c46dfa2e49a8fc192d70a46711dfb61220b6ffb2e62bc04)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-gnustl-platform-12-armeabi.zip/lib/armeabi/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "armeabi-v7a")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-gnustl-platform-12-armeabi-v7a.zip 335631 c2852f9a88239fcf40c0f6e42dd8fe58c583665cd1cc1bace24327353bef466f)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-gnustl-platform-12-armeabi-v7a.zip/lib/armeabi-v7a/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "x86")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-gnustl-platform-12-x86.zip 378897 5392d9d7e92f70cbed3b12758e1dd9f360297d7a90f8b0d0f811eb998b875c49)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-gnustl-platform-12-x86.zip/lib/x86/libfreetype.a")
        else()
          message(FATAL_ERROR "Android ABI ${cdep_determined_android_abi} is not supported by com.github.jomof:freetype:2.6.2-rev14 for platform ${cdep_determined_android_platform_level}. Supported: armeabi armeabi-v7a x86  CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
        endif()
      else()
        message(FATAL_ERROR "Android API level ${cdep_determined_android_platform_level} is not supported by com.github.jomof:freetype:2.6.2-rev14 CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
      endif()
    elseif(cdep_determined_android_runtime STREQUAL "gnustl_static")
      if(cdep_determined_android_platform_level GREATER 20)
        if(cdep_determined_android_abi STREQUAL "armeabi")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-gnustl-platform-21-armeabi.zip 369041 bdb5e3e80b85b24fb635bc214c319ee71043c22ef1943f157353b512e069e4f7)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-gnustl-platform-21-armeabi.zip/lib/armeabi/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "armeabi-v7a")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-gnustl-platform-21-armeabi-v7a.zip 335622 98674f947353852ae5440491a8f73f33ccc480a7aea4f20b6e0a82b71f300417)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-gnustl-platform-21-armeabi-v7a.zip/lib/armeabi-v7a/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "arm64-v8a")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-gnustl-platform-21-arm64-v8a.zip 374694 8971488ad8f9af7ba1a51fd060fe8e167fe706fa7676c6f0c13a407f775b6ea0)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-gnustl-platform-21-arm64-v8a.zip/lib/arm64-v8a/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "x86")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-gnustl-platform-21-x86.zip 378894 4293869f6aaec95f1428af3c5add6d6982be7cd4fcadac2aff1b718c659d4687)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-gnustl-platform-21-x86.zip/lib/x86/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "x86_64")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-gnustl-platform-21-x86_64.zip 395151 608dfb496a36aa2ebdd10c0175617e4ec41deedade88eafe4340c64455b9bb5b)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-gnustl-platform-21-x86_64.zip/lib/x86_64/libfreetype.a")
        else()
          message(FATAL_ERROR "Android ABI ${cdep_determined_android_abi} is not supported by com.github.jomof:freetype:2.6.2-rev14 for platform ${cdep_determined_android_platform_level}. Supported: armeabi armeabi-v7a arm64-v8a x86 x86_64  CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
        endif()
      elseif(cdep_determined_android_platform_level GREATER 11)
        if(cdep_determined_android_abi STREQUAL "armeabi")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-gnustl-platform-12-armeabi.zip 369035 3e09bf646af1a7614c46dfa2e49a8fc192d70a46711dfb61220b6ffb2e62bc04)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-gnustl-platform-12-armeabi.zip/lib/armeabi/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "armeabi-v7a")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-gnustl-platform-12-armeabi-v7a.zip 335631 c2852f9a88239fcf40c0f6e42dd8fe58c583665cd1cc1bace24327353bef466f)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-gnustl-platform-12-armeabi-v7a.zip/lib/armeabi-v7a/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "x86")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-gnustl-platform-12-x86.zip 378897 5392d9d7e92f70cbed3b12758e1dd9f360297d7a90f8b0d0f811eb998b875c49)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-gnustl-platform-12-x86.zip/lib/x86/libfreetype.a")
        else()
          message(FATAL_ERROR "Android ABI ${cdep_determined_android_abi} is not supported by com.github.jomof:freetype:2.6.2-rev14 for platform ${cdep_determined_android_platform_level}. Supported: armeabi armeabi-v7a x86  CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
        endif()
      else()
        message(FATAL_ERROR "Android API level ${cdep_determined_android_platform_level} is not supported by com.github.jomof:freetype:2.6.2-rev14 CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
      endif()
    elseif(cdep_determined_android_runtime STREQUAL "stlport_shared")
      if(cdep_determined_android_platform_level GREATER 20)
        if(cdep_determined_android_abi STREQUAL "armeabi")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-stlport-platform-21-armeabi.zip 369032 f1ecd5981750d36078ee9b527ee59a3a9126ab4eb392c7efc12bac58c4d5b58d)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-stlport-platform-21-armeabi.zip/lib/armeabi/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "armeabi-v7a")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-stlport-platform-21-armeabi-v7a.zip 335635 44fb512d2884509847690963bf1c12d9594a4282c358da9f6c48cacb919ec5a2)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-stlport-platform-21-armeabi-v7a.zip/lib/armeabi-v7a/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "arm64-v8a")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-stlport-platform-21-arm64-v8a.zip 374706 68362d2ef96a0e34055280a4f6cc5bfa223a5774c314df48373a4e47712ad85e)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-stlport-platform-21-arm64-v8a.zip/lib/arm64-v8a/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "x86")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-stlport-platform-21-x86.zip 378918 50c9667c3df276c1311810ba74f911a213866eec3eaea32782e3cc4635bff97f)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-stlport-platform-21-x86.zip/lib/x86/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "x86_64")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-stlport-platform-21-x86_64.zip 395137 05e9f8a848b548bb9893330b8bafb8658c77e87fd9f956bcc442b5c263237705)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-stlport-platform-21-x86_64.zip/lib/x86_64/libfreetype.a")
        else()
          message(FATAL_ERROR "Android ABI ${cdep_determined_android_abi} is not supported by com.github.jomof:freetype:2.6.2-rev14 for platform ${cdep_determined_android_platform_level}. Supported: armeabi armeabi-v7a arm64-v8a x86 x86_64  CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
        endif()
      elseif(cdep_determined_android_platform_level GREATER 11)
        if(cdep_determined_android_abi STREQUAL "armeabi")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-stlport-platform-12-armeabi.zip 369043 6aa3418f6dea7fd01ecc0da0d52460faaadfdc604ccde36792930a5c00481580)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-stlport-platform-12-armeabi.zip/lib/armeabi/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "armeabi-v7a")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-stlport-platform-12-armeabi-v7a.zip 335626 1439804cccf6dd3be202aef336c8672fd18788eb4b050b4dbf7f679395446066)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-stlport-platform-12-armeabi-v7a.zip/lib/armeabi-v7a/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "x86")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-stlport-platform-12-x86.zip 378898 1065bef9b557705ddc7bee923250e93567ce7a6c1dca0c2d37a001d1d010d840)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-stlport-platform-12-x86.zip/lib/x86/libfreetype.a")
        else()
          message(FATAL_ERROR "Android ABI ${cdep_determined_android_abi} is not supported by com.github.jomof:freetype:2.6.2-rev14 for platform ${cdep_determined_android_platform_level}. Supported: armeabi armeabi-v7a x86  CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
        endif()
      else()
        message(FATAL_ERROR "Android API level ${cdep_determined_android_platform_level} is not supported by com.github.jomof:freetype:2.6.2-rev14 CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
      endif()
    elseif(cdep_determined_android_runtime STREQUAL "stlport_static")
      if(cdep_determined_android_platform_level GREATER 20)
        if(cdep_determined_android_abi STREQUAL "armeabi")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-stlport-platform-21-armeabi.zip 369032 f1ecd5981750d36078ee9b527ee59a3a9126ab4eb392c7efc12bac58c4d5b58d)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-stlport-platform-21-armeabi.zip/lib/armeabi/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "armeabi-v7a")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-stlport-platform-21-armeabi-v7a.zip 335635 44fb512d2884509847690963bf1c12d9594a4282c358da9f6c48cacb919ec5a2)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-stlport-platform-21-armeabi-v7a.zip/lib/armeabi-v7a/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "arm64-v8a")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-stlport-platform-21-arm64-v8a.zip 374706 68362d2ef96a0e34055280a4f6cc5bfa223a5774c314df48373a4e47712ad85e)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-stlport-platform-21-arm64-v8a.zip/lib/arm64-v8a/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "x86")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-stlport-platform-21-x86.zip 378918 50c9667c3df276c1311810ba74f911a213866eec3eaea32782e3cc4635bff97f)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-stlport-platform-21-x86.zip/lib/x86/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "x86_64")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-stlport-platform-21-x86_64.zip 395137 05e9f8a848b548bb9893330b8bafb8658c77e87fd9f956bcc442b5c263237705)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-stlport-platform-21-x86_64.zip/lib/x86_64/libfreetype.a")
        else()
          message(FATAL_ERROR "Android ABI ${cdep_determined_android_abi} is not supported by com.github.jomof:freetype:2.6.2-rev14 for platform ${cdep_determined_android_platform_level}. Supported: armeabi armeabi-v7a arm64-v8a x86 x86_64  CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
        endif()
      elseif(cdep_determined_android_platform_level GREATER 11)
        if(cdep_determined_android_abi STREQUAL "armeabi")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-stlport-platform-12-armeabi.zip 369043 6aa3418f6dea7fd01ecc0da0d52460faaadfdc604ccde36792930a5c00481580)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-stlport-platform-12-armeabi.zip/lib/armeabi/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "armeabi-v7a")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-stlport-platform-12-armeabi-v7a.zip 335626 1439804cccf6dd3be202aef336c8672fd18788eb4b050b4dbf7f679395446066)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-stlport-platform-12-armeabi-v7a.zip/lib/armeabi-v7a/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "x86")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-stlport-platform-12-x86.zip 378898 1065bef9b557705ddc7bee923250e93567ce7a6c1dca0c2d37a001d1d010d840)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-stlport-platform-12-x86.zip/lib/x86/libfreetype.a")
        else()
          message(FATAL_ERROR "Android ABI ${cdep_determined_android_abi} is not supported by com.github.jomof:freetype:2.6.2-rev14 for platform ${cdep_determined_android_platform_level}. Supported: armeabi armeabi-v7a x86  CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
        endif()
      else()
        message(FATAL_ERROR "Android API level ${cdep_determined_android_platform_level} is not supported by com.github.jomof:freetype:2.6.2-rev14 CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
      endif()
    elseif(cdep_determined_android_runtime STREQUAL "none")
      if(cdep_determined_android_platform_level GREATER 20)
        if(cdep_determined_android_abi STREQUAL "armeabi")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-cxx-platform-21-armeabi.zip 369033 1d20827c589d35b8aac7445e9c35c32479591a4802d8050a0b578f8eeb432908)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-cxx-platform-21-armeabi.zip/lib/armeabi/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "armeabi-v7a")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-cxx-platform-21-armeabi-v7a.zip 335629 2b0f9a17b3793efb4fd9174f55852d7b8b6e594afedc0bb479071c137afc8f84)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-cxx-platform-21-armeabi-v7a.zip/lib/armeabi-v7a/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "arm64-v8a")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-cxx-platform-21-arm64-v8a.zip 374701 a0672b0ce2ce2a932ffe7998c6203ebfecd804cd378cb9e5c83f00a93b0dbe82)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-cxx-platform-21-arm64-v8a.zip/lib/arm64-v8a/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "x86")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-cxx-platform-21-x86.zip 378894 6db4af622adcd938cf39eb5c95523c8e6b984d09271f40add478bcdee5e4562a)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-cxx-platform-21-x86.zip/lib/x86/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "x86_64")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-cxx-platform-21-x86_64.zip 395132 e4a6c218dc85904f11ff599f5eefcaabdc89d11e5c6f589c4d41a7000fd42b60)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-cxx-platform-21-x86_64.zip/lib/x86_64/libfreetype.a")
        else()
          message(FATAL_ERROR "Android ABI ${cdep_determined_android_abi} is not supported by com.github.jomof:freetype:2.6.2-rev14 for platform ${cdep_determined_android_platform_level}. Supported: armeabi armeabi-v7a arm64-v8a x86 x86_64  CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
        endif()
      elseif(cdep_determined_android_platform_level GREATER 11)
        if(cdep_determined_android_abi STREQUAL "armeabi")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-cxx-platform-12-armeabi.zip 369025 2588edf3e855fc89e858a40b0c9a8b7e5f4778681bf55d727c209b3d610a2d37)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-cxx-platform-12-armeabi.zip/lib/armeabi/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "armeabi-v7a")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-cxx-platform-12-armeabi-v7a.zip 335630 a0c776b84f32640c49f4a064a98df8b30f1c5c7e979f672ff56f103f730b1821)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-cxx-platform-12-armeabi-v7a.zip/lib/armeabi-v7a/libfreetype.a")
        elseif(cdep_determined_android_abi STREQUAL "x86")
          execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-android-cxx-platform-12-x86.zip 378892 2601b9f9d2f738a3880d1bb7e5d2e3debc8d41f61c04d12e27dfe9705c231d14)
          target_link_libraries(${target} "${exploded_archive_folder}/freetype-android-cxx-platform-12-x86.zip/lib/x86/libfreetype.a")
        else()
          message(FATAL_ERROR "Android ABI ${cdep_determined_android_abi} is not supported by com.github.jomof:freetype:2.6.2-rev14 for platform ${cdep_determined_android_platform_level}. Supported: armeabi armeabi-v7a x86  CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
        endif()
      else()
        message(FATAL_ERROR "Android API level ${cdep_determined_android_platform_level} is not supported by com.github.jomof:freetype:2.6.2-rev14 CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
      endif()
    else()
      message(FATAL_ERROR "Android runtime '${cdep_determined_android_runtime}' is not supported by com.github.jomof:freetype:2.6.2-rev14. Supported: c++ gnustl stlport  CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
    endif()
  elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    get_filename_component(osx_sysroot_sdk_name ${CMAKE_OSX_SYSROOT} NAME)
    string(FIND ${osx_sysroot_sdk_name} "." last_dot_position REVERSE)
    string(SUBSTRING ${osx_sysroot_sdk_name} "0" ${last_dot_position} combined_platform_and_sdk)

    if(CMAKE_OSX_ARCHITECTURES STREQUAL "armv7")
      if(combined_platform_and_sdk STREQUAL "iPhoneOS9.3")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneOS-architecture-armv7-sdk-9.3.zip 345764 058724cb084a3d336142a242aeaf157169160593513c3a5e380fcf5239bd6e06)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneOS-architecture-armv7-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneOS.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneOS-architecture-armv7-sdk-9.3.zip 345764 058724cb084a3d336142a242aeaf157169160593513c3a5e380fcf5239bd6e06)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneOS-architecture-armv7-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneOS.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneOS-architecture-armv7s-sdk-9.3.zip 344839 d964627af613468aae39151de58ac53065ce417f67b2705ccbb73b03c4c612ac)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneOS-architecture-armv7s-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneOS.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneOS-architecture-arm64-sdk-9.3.zip 383186 3653c7a89790bab7c6db82405a6df32009622aedf39c2b8677b2ce866bc848a8)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneOS-architecture-arm64-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneSimulator.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneSimulator-architecture-i386-sdk-9.3.zip 372790 9a8f2f4545c726aa5d99667fca1cfde1bfa5fc022bb8a46e890e9eb89312bb4d)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneSimulator-architecture-i386-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneSimulator.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneSimulator-architecture-x86_64-sdk-9.3.zip 405278 dd8116af778df13954c2b445ff0b543c1b9e18ca25d6670f53a1886aeb844ea8)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneSimulator-architecture-x86_64-sdk-9.3.zip/lib/libfreetype.a")
      else()
        message(FATAL_ERROR "OSX SDK ${combined_platform_and_sdk} is not supported by com.github.jomof:freetype:2.6.2-rev14 and architecture armv7. Supported: iPhoneOS9.3  CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
      endif()
    elseif(CMAKE_OSX_ARCHITECTURES STREQUAL "armv7s")
      if(combined_platform_and_sdk STREQUAL "iPhoneOS9.3")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneOS-architecture-armv7s-sdk-9.3.zip 344839 d964627af613468aae39151de58ac53065ce417f67b2705ccbb73b03c4c612ac)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneOS-architecture-armv7s-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneOS.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneOS-architecture-armv7-sdk-9.3.zip 345764 058724cb084a3d336142a242aeaf157169160593513c3a5e380fcf5239bd6e06)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneOS-architecture-armv7-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneOS.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneOS-architecture-armv7s-sdk-9.3.zip 344839 d964627af613468aae39151de58ac53065ce417f67b2705ccbb73b03c4c612ac)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneOS-architecture-armv7s-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneOS.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneOS-architecture-arm64-sdk-9.3.zip 383186 3653c7a89790bab7c6db82405a6df32009622aedf39c2b8677b2ce866bc848a8)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneOS-architecture-arm64-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneSimulator.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneSimulator-architecture-i386-sdk-9.3.zip 372790 9a8f2f4545c726aa5d99667fca1cfde1bfa5fc022bb8a46e890e9eb89312bb4d)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneSimulator-architecture-i386-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneSimulator.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneSimulator-architecture-x86_64-sdk-9.3.zip 405278 dd8116af778df13954c2b445ff0b543c1b9e18ca25d6670f53a1886aeb844ea8)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneSimulator-architecture-x86_64-sdk-9.3.zip/lib/libfreetype.a")
      else()
        message(FATAL_ERROR "OSX SDK ${combined_platform_and_sdk} is not supported by com.github.jomof:freetype:2.6.2-rev14 and architecture armv7s. Supported: iPhoneOS9.3  CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
      endif()
    elseif(CMAKE_OSX_ARCHITECTURES STREQUAL "arm64")
      if(combined_platform_and_sdk STREQUAL "iPhoneOS9.3")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneOS-architecture-arm64-sdk-9.3.zip 383186 3653c7a89790bab7c6db82405a6df32009622aedf39c2b8677b2ce866bc848a8)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneOS-architecture-arm64-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneOS.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneOS-architecture-armv7-sdk-9.3.zip 345764 058724cb084a3d336142a242aeaf157169160593513c3a5e380fcf5239bd6e06)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneOS-architecture-armv7-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneOS.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneOS-architecture-armv7s-sdk-9.3.zip 344839 d964627af613468aae39151de58ac53065ce417f67b2705ccbb73b03c4c612ac)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneOS-architecture-armv7s-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneOS.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneOS-architecture-arm64-sdk-9.3.zip 383186 3653c7a89790bab7c6db82405a6df32009622aedf39c2b8677b2ce866bc848a8)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneOS-architecture-arm64-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneSimulator.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneSimulator-architecture-i386-sdk-9.3.zip 372790 9a8f2f4545c726aa5d99667fca1cfde1bfa5fc022bb8a46e890e9eb89312bb4d)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneSimulator-architecture-i386-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneSimulator.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneSimulator-architecture-x86_64-sdk-9.3.zip 405278 dd8116af778df13954c2b445ff0b543c1b9e18ca25d6670f53a1886aeb844ea8)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneSimulator-architecture-x86_64-sdk-9.3.zip/lib/libfreetype.a")
      else()
        message(FATAL_ERROR "OSX SDK ${combined_platform_and_sdk} is not supported by com.github.jomof:freetype:2.6.2-rev14 and architecture arm64. Supported: iPhoneOS9.3  CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
      endif()
    elseif(CMAKE_OSX_ARCHITECTURES STREQUAL "i386")
      if(combined_platform_and_sdk STREQUAL "iPhoneSimulator9.3")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneSimulator-architecture-i386-sdk-9.3.zip 372790 9a8f2f4545c726aa5d99667fca1cfde1bfa5fc022bb8a46e890e9eb89312bb4d)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneSimulator-architecture-i386-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneOS.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneOS-architecture-armv7-sdk-9.3.zip 345764 058724cb084a3d336142a242aeaf157169160593513c3a5e380fcf5239bd6e06)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneOS-architecture-armv7-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneOS.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneOS-architecture-armv7s-sdk-9.3.zip 344839 d964627af613468aae39151de58ac53065ce417f67b2705ccbb73b03c4c612ac)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneOS-architecture-armv7s-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneOS.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneOS-architecture-arm64-sdk-9.3.zip 383186 3653c7a89790bab7c6db82405a6df32009622aedf39c2b8677b2ce866bc848a8)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneOS-architecture-arm64-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneSimulator.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneSimulator-architecture-i386-sdk-9.3.zip 372790 9a8f2f4545c726aa5d99667fca1cfde1bfa5fc022bb8a46e890e9eb89312bb4d)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneSimulator-architecture-i386-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneSimulator.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneSimulator-architecture-x86_64-sdk-9.3.zip 405278 dd8116af778df13954c2b445ff0b543c1b9e18ca25d6670f53a1886aeb844ea8)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneSimulator-architecture-x86_64-sdk-9.3.zip/lib/libfreetype.a")
      else()
        message(FATAL_ERROR "OSX SDK ${combined_platform_and_sdk} is not supported by com.github.jomof:freetype:2.6.2-rev14 and architecture i386. Supported: iPhoneSimulator9.3  CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
      endif()
    elseif(CMAKE_OSX_ARCHITECTURES STREQUAL "x86_64")
      if(combined_platform_and_sdk STREQUAL "iPhoneSimulator9.3")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneSimulator-architecture-x86_64-sdk-9.3.zip 405278 dd8116af778df13954c2b445ff0b543c1b9e18ca25d6670f53a1886aeb844ea8)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneSimulator-architecture-x86_64-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneOS.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneOS-architecture-armv7-sdk-9.3.zip 345764 058724cb084a3d336142a242aeaf157169160593513c3a5e380fcf5239bd6e06)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneOS-architecture-armv7-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneOS.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneOS-architecture-armv7s-sdk-9.3.zip 344839 d964627af613468aae39151de58ac53065ce417f67b2705ccbb73b03c4c612ac)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneOS-architecture-armv7s-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneOS.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneOS-architecture-arm64-sdk-9.3.zip 383186 3653c7a89790bab7c6db82405a6df32009622aedf39c2b8677b2ce866bc848a8)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneOS-architecture-arm64-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneSimulator.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneSimulator-architecture-i386-sdk-9.3.zip 372790 9a8f2f4545c726aa5d99667fca1cfde1bfa5fc022bb8a46e890e9eb89312bb4d)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneSimulator-architecture-i386-sdk-9.3.zip/lib/libfreetype.a")
      elseif(combined_platform_and_sdk MATCHES "$iPhoneSimulator.*")
        execute_process(COMMAND /opt/homebrew/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home/bin/java -classpath /Users/gauravk/.cdep/bootstrap/downloads/969779654/cdep-0.8.30.jar io.cdep.CDep --working-folder /Users/gauravk/Desktop/playground/AndroidMath/mathdisplaylib/. fetch-archive com.github.jomof:freetype:2.6.2-rev14 https://github.com/jomof/freetype/releases/download/2.6.2-rev14/freetype-ios-platform-iPhoneSimulator-architecture-x86_64-sdk-9.3.zip 405278 dd8116af778df13954c2b445ff0b543c1b9e18ca25d6670f53a1886aeb844ea8)
        target_link_libraries(${target} "${exploded_archive_folder}/freetype-ios-platform-iPhoneSimulator-architecture-x86_64-sdk-9.3.zip/lib/libfreetype.a")
      else()
        message(FATAL_ERROR "OSX SDK ${combined_platform_and_sdk} is not supported by com.github.jomof:freetype:2.6.2-rev14 and architecture x86_64. Supported: iPhoneSimulator9.3  CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
      endif()
    else()
      message(FATAL_ERROR "OSX architecture ${CMAKE_OSX_ARCHITECTURES} is not supported by com.github.jomof:freetype:2.6.2-rev14. Supported:  armv7 armv7s arm64 i386 x86_64 CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
    endif()
  else()
    message(FATAL_ERROR "Target platform ${CMAKE_SYSTEM_NAME} is not supported by com.github.jomof:freetype:2.6.2-rev14. Supported: Android Darwin CMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} ANDROID_SYSTEM_VERSION=${ANDROID_SYSTEM_VERSION} CMAKE_ANDROID_STL_TYPE=${CMAKE_ANDROID_STL_TYPE} ANDROID_STL=${ANDROID_STL}")
  endif()
endfunction(add_cdep_freetype_dependency)

function(add_all_cdep_dependencies target)
  add_cdep_freetype_dependency(${target})
endfunction(add_all_cdep_dependencies)
